config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
               sessions: 'session/sessions'
             }

  resources :timers
  resources :entries, only: [:create, :update, :destroy] do
    post :stop_timer, on: :member
  end

  resource :profile, only: [:show, :update]

  namespace :admin do
    resources :reports
  end

  root to: 'timers#index'
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :project
  belongs_to :user

  scope :for_date, ->(date) { where(recorded_date: date) }

  delegate :name, to: :project, prefix: true
  delegate :client_name, to: :project

  validates :project_id, presence: true
  validates :duration, numericality: true, allow_nil: true

  before_create :start_timer_if_no_duration

  def user_name
    user.display_name
  end

  def company_and_project_name
    "#{client_name} / #{project_name}"
  end

  def running_timer?
    duration.nil? && start_time.present?
  end

  def stop_timer!
    self[:duration] = ((Time.zone.now - start_time) / 60 / 60).round(2)
    save!
  end

  private

  def start_timer_if_no_duration
    return if duration.present? || start_time.present?
    self[:start_time] = Time.now
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_date

  def create
    @new_entry = current_user.entries.new(entry_params)
    if @new_entry.save
      redirect_to timers_path(date: @new_entry.recorded_date.strftime("%Y-%m-%d"))
    else
      # load up the clients for the new entry form to rerender
      @clients = Client.ordered.all
    end
  end

  def update
  end

  def stop_timer
    entry = current_user.entries.find(params[:id])
    entry.stop_timer!
    redirect_to timers_path(date: entry.recorded_date.strftime("%Y-%m-%d"))
  end

  def destroy
  end

  private

  def entry_params
    params.require(:entry).permit(:duration, :notes, :project_id, :recorded_date)
  end
end

app/views/entries/_entry.html.erb
<li class="project">
  <div class="px-4 py-4 sm:px-6">
    <div class="md:flex items-center justify-between w-full">
      <div class="leading-5 font-medium w-4/5">
        <%= entry.company_and_project_name %> 
      </div>
      <div class="flex md:pl-3 pt-2 md:pt-0 w-full">
        <% if entry.running_timer? %>
          <span class="inline-flex rounded-md shadow-sm mt-5">
            <%= button_to 'Stop timer', stop_timer_entry_path(entry), class: 'inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150', remote: true %>
          </span>
        <% else %>
          <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"/>
          </svg>
          <span class="text-sm text-gray-500">
            <%= pluralize(entry.duration, 'hour') %> 
          </span>
        <% end %>
      </div>
    </div>
    <p class="mt-2">
      <%= entry.notes %>
    </p>
  </div>
</li>

app/views/entries/create.js.erb
$("#enter_time").replaceWith("<%= j render "timers/new_entry" %>");
$(document).trigger('turbolinks:load');