config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
               sessions: 'session/sessions'
             }

  resources :timers
  resources :entries, only: [:create, :update, :destroy] do
    post :stop_timer, on: :member
  end

  resource :profile, only: [:show, :update]

  namespace :admin do
    resources :reports
  end

  root to: 'timers#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Timer</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>

        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.0.1/dist/alpine.js" defer></script>

        <div>
            <nav x-data="{ open: false }" @keydown.window.escape="open = false" class="bg-gray-800">
                <div id="desktop-nav" class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div class="flex items-center justify-between h-16">
                        <div class="flex items-center">
                            <div class="hidden md:block">
                                <div class="ml-10 flex items-baseline">
                                    <%= render 'shared/desktop_nav_link', href: timers_path, text: "Timesheets", active: @page == :timers %>
                                    <% if current_user.admin? %>
                                        <%= render 'shared/desktop_nav_link', href: admin_reports_path, text: "Reports", active: @page == :reports %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                        <div class="hidden md:block">
                            <div class="ml-4 flex items-center md:ml-6">
                                <p class="text-gray-200">Hello, <span class="font-bold"><%= current_user.display_name %></span></p>
                                <div @click.away="open = false" class="ml-3 relative" x-data="{ open: false }">
                                    <div>
                                        <button @click="open = !open" class="max-w-xs flex items-center text-sm rounded-full text-white focus:outline-none focus:shadow-solid" id="user-menu" aria-label="User menu" aria-haspopup="true" x-bind:aria-expanded="open">
                                            <img class="h-8 w-8 rounded-full" src="<%= current_user_gravatar_url %>" alt="" />
                                        </button>
                                    </div>
                                    <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg">
                                        <div class="py-1 rounded-md bg-white shadow-xs">
                                            <a href="<%= profile_path %>" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Your Profile</a>
                                            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="-mr-2 flex md:hidden">
                            <button @click="open = !open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:bg-gray-700 focus:text-white" x-bind:aria-label="open ? 'Close main menu' : 'Main menu'" x-bind:aria-expanded="open">
                                <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                                    <path :class="{'hidden': open, 'inline-flex': !open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                                    <path :class="{'hidden': !open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
                <div id="mobile-nav" :class="{'block': open, 'hidden': !open}" class="hidden md:hidden">
                    <div class="px-2 pt-2 pb-3 sm:px-3">
                        <%= render "shared/mobile_nav_link", href: timers_path, text: "Timesheets", active: @page == :timers %>
                        <% if current_user.admin? %>
                            <%= render "shared/mobile_nav_link", href: admin_reports_path, text: "Reports", active: @page == :reports %>
                        <% end %>
                    </div>
                    <div class="pt-4 pb-3 border-t border-gray-700">
                        <div class="flex items-center px-5">
                            <div class="flex-shrink-0">
                                <img class="h-10 w-10 rounded-full" src="<%= current_user_gravatar_url %>" alt="" />
                            </div>
                            <div class="ml-3">
                                <div class="text-base font-medium leading-none text-white"><%= current_user.display_name %></div>
                                <div class="mt-1 text-sm font-medium leading-none text-gray-400"><%= current_user.email %></div>
                            </div>
                        </div>
                        <div class="mt-3 px-2" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
                            <a href="<%= profile_path %>" class="block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700" role="menuitem">Your Profile</a>
                            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700", role: "menuitem" %>
                        </div>
                    </div>
                </div>
            </nav>
            <% if @header_text.present? %>
                <header class="bg-white shadow-sm">
                    <div class="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8">
                        <h1 class="text-center text-lg leading-6 font-semibold text-gray-900">
                            <%= @header_text %>
                        </h1>
                    </div>
                </header>
            <% end %>

            <% if current_user.name.blank? && @page != :profile %>
                <div class="bg-orange-100 border-t border-b border-orange-500 text-orange-700 px-4 py-3 mb-4" role="alert">
                    <p class="font-bold">Hey, you can set your name!</p>
                    <p class="text-sm">Did you know you can set a custom name so we know what to call you besides your email address? Set that up in <a href="<%= profile_path %>" class="underline font-bold hover:text-orange-600 transition ease-in-out">your profile</a>!</p>
                </div>
            <% end %>

            <% if flash.notice.present? %>
                <div class="bg-green-100 border-t border-b border-green-500 text-green-700 px-4 py-3 mb-4" role="alert">
                    <p class="font-bold">Success!</p>
                    <p class="text-sm"><%= flash.notice %></p>
                </div>
            <% end %>

            <% if flash.alert.present? %>
                <div class="bg-green-100 border-t border-b border-green-500 text-green-700 px-4 py-3 mb-4" role="alert">
                    <p class="font-bold">Oh No!</p>
                    <p class="text-sm"><%= flash.alert %></p>
                </div>
            <% end %>

            <main>
                <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
                    <%= yield %>
                </div>
            </main>
        </div>


  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Timer</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <div>
            <main>
                <div class="bg-white overflow-hidden shadow rounded-lg">
                    <div class="px-4 py-5 sm:p-6">
                        <%= yield %>
                    </div>
                </div>
            </main>
        </div>
  </body>
</html>